# Generated by Django 3.2.5 on 2021-08-02 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.TextField()),
                ('carbohydrateContent', models.TextField()),
                ('cholesterolContent', models.TextField()),
                ('fatContent', models.TextField()),
                ('fiberContent', models.TextField()),
                ('proteinContent', models.TextField()),
                ('saturatedFatContent', models.TextField()),
                ('servingSize', models.TextField()),
                ('sodiumContent', models.TextField()),
                ('sugarContent', models.TextField()),
                ('transFatContent', models.TextField()),
                ('unsaturatedFatContent', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webAddress', models.URLField()),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('author', models.TextField()),
                ('datePublished', models.DateField()),
                ('publisher', models.TextField()),
                ('estimatedCost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prepTime', models.DurationField()),
                ('totalTime', models.DurationField()),
                ('cookTime', models.DurationField()),
                ('cookingMethod', models.TextField()),
                ('recipeCategory', models.TextField()),
                ('recipeCuisine', models.TextField()),
                ('recipeIngredient', models.TextField()),
                ('recipeInstructions', models.TextField()),
                ('suitableForDiet', models.TextField()),
                ('nutrition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.nutritionalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.recipe')),
            ],
        ),
    ]
