# Generated by Django 3.2.5 on 2021-08-05 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_recipe_datesaved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cookTime',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cookingMethod',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='estimatedCost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='nutrition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.nutritionalinfo'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prepTime',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='publisher',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipeCategory',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipeCuisine',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='suitableForDiet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='totalTime',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
