# Generated by Django 3.2.5 on 2021-08-05 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_auto_20210805_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='nutrition',
        ),
        migrations.AddField(
            model_name='nutritionalinfo',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='viewer.recipe'),
            preserve_default=False,
        ),
    ]
