version: '3'

services:
  web:
    build: .
    container_name: recipe_viewer
    restart: unless-stopped
    ports:
      - "${PORT}:8000"
    volumes:
      - ./db.sqlite3:/APP/db.sqlite3
      - ./viewer/static/:/APP/viewer/static